//
//  AuthScreenModels.swift
//  M1HW7_EgorSaushkin
//
//  Created by Egor SAUSHKIN on 22.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AuthScreen {
	enum Model {
		struct Request {
			var login: String
			var pass: String
		}
		
		struct Response {
			var success: Bool
		}
		
		struct ViewModel {
			var message: String
		}
	}
}
