//
//  AuthScreenInteractor.swift
//  M1HW7_EgorSaushkin
//
//  Created by Egor SAUSHKIN on 22.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthScreenBusinessLogic {
	func processAuthorisation(request: AuthScreen.Model.Request)
}

protocol AuthScreenDataStore {
}

class AuthScreenInteractor: AuthScreenBusinessLogic, AuthScreenDataStore {
	var presenter: AuthScreenPresentationLogic?
	var worker: AuthScreenWorker?
	
	func processAuthorisation(request: AuthScreen.Model.Request) {
		worker = AuthScreenWorker()
		let result = worker?.checkAuthData(login: request.login, pass: request.pass)
		let response = AuthScreen.Model.Response(success: result!)
		presenter?.present(response: response)
	}
}
