//
//  AuthScreenPresenter.swift
//  M1HW7_EgorSaushkin
//
//  Created by Egor SAUSHKIN on 22.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthScreenPresentationLogic {
	func present(response: AuthScreen.Model.Response)
}

class AuthScreenPresenter: AuthScreenPresentationLogic {
	weak var viewController: AuthScreenDisplayLogic?
	
	func present(response: AuthScreen.Model.Response) {
		if response.success == true {
			let viewModel = AuthScreen.Model.ViewModel(message: "Login successful")
			viewController?.displayView(viewModel: viewModel)
		} else {
			let viewModel = AuthScreen.Model.ViewModel(message: "Error")
			viewController?.displayView(viewModel: viewModel)
		}
	}
}
