//
//  AuthScreenWorker.swift
//  M1HW7_EgorSaushkin
//
//  Created by Egor SAUSHKIN on 22.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class AuthScreenWorker {
	private var login: String = "Admin"
	private var pass: String = "pa$$32!"
	
	func checkAuthData(login: String, pass: String) -> Bool {
		if login == self.login && pass == self.pass {
			return true
		}
		return false
	}
}
