//
//  ToDoPresenter.swift
//  M1HW7_EgorSaushkin
//
//  Created by Egor SAUSHKIN on 22.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ToDoPresentationLogic {
	func present(response: ToDo.Model.Response)
}

class ToDoPresenter: ToDoPresentationLogic {
	weak var viewController: ToDoDisplayLogic?
	
	// MARK: Do something

	func present(response: ToDo.Model.Response) {
		let viewModel = ToDo.Model.ViewModel(
			section: response.section,
			tasks: response.tasks,
			title: response.title,
			numberOfRows: response.numberOfRows)
		viewController?.display(viewModel: viewModel)
	}
}
