//
//  ToDoModels.swift
//  M1HW7_EgorSaushkin
//
//  Created by Egor SAUSHKIN on 22.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ToDo {
	enum Model {
		struct Request {
			var section: Int
		}
		
		struct Response {
			var section: Int
			var tasks: [Task]
			var title: String
			var numberOfRows: Int
		}
		
		struct ViewModel {
			var section: Int
			var tasks: [Task]
			var title: String
			var numberOfRows: Int
		}
	}
}
